## Numpy_basic_Function

In [16]:
import numpy as n
a=n.array([89,809,99])
print(a) 
print(a.size)          #size of array
print(a.itemsize)      #size of datatype of value present in array
print(a.ndim)          #dimension of array
print(a.shape)         #shape of array
print(a.dtype)         #datatype of array

[ 89 809  99]
3
4
1
(3,)
int32


In [8]:
import numpy as n
l=[91,82,93,94,95,89]       #creating 1d array from list using numpy
a=n.array(l)
for ele in a:
    print(ele)
print(a.size)
print(a.ndim)
print(a.shape)

91
82
93
94
95
89
6
1
(6,)


In [22]:
import numpy as n
l=[[1,2,3],[4,5,6]]
a=n.array(l)
#for ele in a:
    #print(ele)
for ele in a:
    for item in ele:
        print(item)         # taking each element from the row

print(a.ndim)
print(a.shape)

1
2
3
4
5
6
2
(2, 3)


In [23]:
import numpy as a
l=[1,2,3]
a=n.array(l,dtype=complex)       #give 1 d array of complex type
print(a)

[1.+0.j 2.+0.j 3.+0.j]


In [25]:
import numpy as n
a=n.array([[10,20,30],[40,50,60],[70,80,90]])
a

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [27]:
print(a[1:3,1:3])  #slicing is done to get sub-array of lowermost right side


[[50 60]
 [80 90]]


In [28]:
print(a[:,:])   #give u full 3d-array

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [45]:
import numpy as a
size=int(input("Enter size: "))
arr=a.ndarray(shape=(size),dtype=int)

for i in range(size):
    ele=int(input())
    arr[i]=ele              #creating user-define 1- Dimensional Array
print(arr)

Enter size: 9
89
78
80
98
97
96
99
90
87
[89 78 80 98 97 96 99 90 87]


In [44]:
import numpy
def arrays(arr):
    # complete this function
    # use numpy.array
    a=numpy.array(arr,dtype=float)
    return a[::-1]

arr = input().split(' ')
result = arrays(arr)
print(result)                   #Hackerrank numpy array question

1 2 3 4 -8 -10
[-10.  -8.   4.   3.   2.   1.]


In [ ]:
import numpy as n
row=int(input())
col=int(input())                           
a=n.ndarray(shape=(row,col),dtype=float)      #user-defined 2-d array using numpy
for i in range(row):
    for j in range(col):
        a[i,j]=int(input())
print(a)
