# Numpy Basic
1.First install numpy module in cmd<br>
2.Command:pip install numpy

In [2]:
import numpy as n             #import numpy module in program
a=n.array([89,90,90])
a

array([89, 90, 90])

In [3]:
import numpy as n          
help(n.array)       #this command gives all the  instructions

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', 'C', 'F'}, optional
        Specify the memory layout of the array. If object is not an array, the
        newly c

In [4]:
import numpy as n
a=n.array([1,2,3])
b=n.array([4,5,6,])          
c=a+b                           #simple pprogram to show summation of two array
print(c)

[5 7 9]


In [6]:
import numpy as n
a=n.array([89,90,99],dtype=complex)       #dtype:it help ous to assign desired data-type for the array.
print(a)

[89.+0.j 90.+0.j 99.+0.j]


In [8]:
import numpy as n                            
b=n.array([[1,2],[3,4]])                     #2-D array
print(b)

[[1 2]
 [3 4]]


In [10]:
import numpy as n
b=n.array([[1,2],[3,4]],dtype=complex)    #gives ous 2-D array of complex type
b

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [11]:
import numpy as n
b=n.arange(20)           #gives ous the no from 0 to n-1
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [12]:
import numpy as n
b=n.arange(1,100,5)        
print(b)

[ 1  6 11 16 21 26 31 36 41 46 51 56 61 66 71 76 81 86 91 96]


In [13]:
import numpy as n
b=n.arange(20,dtype='complex')
b

array([ 0.+0.j,  1.+0.j,  2.+0.j,  3.+0.j,  4.+0.j,  5.+0.j,  6.+0.j,
        7.+0.j,  8.+0.j,  9.+0.j, 10.+0.j, 11.+0.j, 12.+0.j, 13.+0.j,
       14.+0.j, 15.+0.j, 16.+0.j, 17.+0.j, 18.+0.j, 19.+0.j])